### ISSUE TITLE
Add Daily Recovered to chart on homepage

### ISSUE THREAD

**Issue by sineckers** [yigiterdev/corona-status#7]
In daily array we has the number of total recovered. Just needed to calculate daily recovered number and add chart.

**Comment by sineckers** [comment]
@yigiterdev can you add "good first issue" label

**Comment by hanupratap** [comment]
Hey, is the issue still open? I would like to work on it.

**Comment by abyigiter** [comment]
The issue is still open. You can work on it.

**Comment by hanupratap** [comment]
The API is down

**Comment by abyigiter** [comment]
We use [Covid19 API](https://covid19api.com/). Sometimes this API doesn't work. We try to find better solution for this.

**Comment by hanupratap** [comment]
Created pull request

**Comment by sineckers** [comment]
@hanupratap just type Closes #7 in your pull request so it will close this issue
